const gameSteps = require('../data/gameSteps');

function gameValidator(req, res, next) {
    // 1. Get the stage ID from the headers (the frontend will send this)
    const stageId = req.headers['x-game-stage'];
    
    // If there's no stage ID, just let the API work normally
    if (!stageId) return next();

    // 2. Find the correct stage in our secret steps file
    const stageNum = parseInt(stageId, 10);
    const step = gameSteps.find(s => s.id === stageNum);
    
    if (!step) {
        return res.status(400).json({ gameError: "Stage not found in the server!" });
    }

    const expected = step.expected;
    
    // 3. Validate HTTP Method
    if (req.method !== expected.method) {
        return res.status(400).json({ gameError: `Wrong HTTP Method. Expected ${expected.method}, but got ${req.method}.` });
    }

    // 4. Validate Path (ignoring query parameters for this check)
    const requestPath = req.originalUrl.split('?')[0]; 
    if (requestPath !== expected.path) {
        return res.status(400).json({ gameError: `Wrong Path. Expected ${expected.path}, but got ${requestPath}.` });
    }

    // 5. Validate Query Parameters (if the stage requires them)
    if (expected.queryParams) {
        for (const key in expected.queryParams) {
            // Using String() to ensure safe comparison between numbers and strings
            if (String(req.query[key]) !== String(expected.queryParams[key])) {
                return res.status(400).json({ gameError: `Missing or incorrect Query Parameter: '${key}'.` });
            }
        }
    }

    // 6. Validate Request Body Structure (Keys)
    if (expected.requiresBody) {
        for (const key of expected.requiredKeys) {
            if (req.body[key] === undefined) {
                return res.status(400).json({ gameError: `Your JSON body is missing the required '${key}' property.` });
            }
        }
    }

    // 7. Deep Content Validation (Stage-Specific Rules)
    switch (stageNum) {
        case 3: 
            // Creating a pastry (POST)
            if (req.body.price <= 0 || req.body.stock < 0) {
                return res.status(400).json({ gameError: "Stage 3: Price must be greater than 0 and stock cannot be negative." });
            }
            break;
            
        case 5: 
            // Creating an order (POST)
            if (req.body.quantity <= 0) {
                return res.status(400).json({ gameError: "Stage 5: You must order at least 1 item (quantity > 0)." });
            }
            break;
            
        case 6: 
            // Kitchen Disaster! Partial Update (PATCH)
            if (req.body.stock !== 0) {
                return res.status(400).json({ gameError: "Stage 6: Almost! You need to set the 'stock' property exactly to 0." });
            }
            // Ensure it's a true PATCH (partial update), not sending the whole object
            if (Object.keys(req.body).length > 2) {
                 return res.status(400).json({ gameError: "Stage 6: Remember, PATCH is for partial updates. Only send the properties that need changing." });
            }
            break;
            
        case 7: 
            // Update Full Order (PUT)
            // PUT requires replacing the whole resource, check if all logical fields exist
            const putKeys = Object.keys(req.body);
            if (!putKeys.includes('customerName') || !putKeys.includes('pastryId') || !putKeys.includes('quantity') || !putKeys.includes('status')) {
                return res.status(400).json({ gameError: "Stage 7: A PUT request requires sending the ENTIRE object. You are missing some properties." });
            }
            break;
            
        // Add more specific case checks for other stages here if needed
    }

    // 🎉 Intercept the response to inject the success header securely
    // We override res.json temporarily so we can check the FINAL status code 
    // generated by the actual API route before confirming the game win.
    const originalJson = res.json;
    res.json = function(data) {
        // Stage 10 expects a 404 (Not Found). All other successful stages expect 200-299.
        if ((res.statusCode >= 200 && res.statusCode < 300) || (stageNum === 10 && res.statusCode === 404)) {
            res.setHeader('X-Game-Result', 'Success');
        }
        // Proceed with sending the actual JSON data back to the client
        return originalJson.call(this, data);
    };

    // Pass control to the real API route
    next();
}

module.exports = gameValidator;